Vagrant.configure("2") do |config|
  config.vm.box = "gusztavvargadr/windows-10"
  
  config.vm.provider "hyperv" do |vb|
  vb.memory = 2048
  vb.cpus = 1
  end
  
  #config.vm.provision "shell", inline: "choco"

  #config.vm.provision "shell", inline: "choco install dotnet-6.0-sdk -y"
  
  #config.vm.provision "shell", inline: "dotnet nuget add source http://192.168.56.1/Baget/v3/index.json"
  #config.vm.provision "shell", inline: "dotnet nuget add source http://192.168.0.104/Baget/v3/index.json"
  #config.vm.provision "shell", inline: "dotnet nuget add source http://172.22.0.1/Baget/v3/index.json"
  
  #config.vm.provision "shell", inline: "dotnet nuget add source http://192.168.56.1:5000/Baget/v3/index.json"
  #config.vm.provision "shell", inline: "dotnet nuget add source http://192.168.0.104:5000/Baget/v3/index.json"
  #config.vm.provision "shell", inline: "dotnet nuget add source http://172.22.0.1:5000/Baget/v3/index.json"
   # config.vm.provision "shell", inline: "dotnet nuget list source"

  config.vm.provision "shell", inline: "dotnet tool install --global mChabanenko --version 1.0.0 --ignore-failed-sources"
end